"""empty message

Revision ID: 727e9e01a96f
Revises: 8d41da330ff5
Create Date: 2018-02-14 15:18:57.557332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727e9e01a96f'
down_revision = '8d41da330ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.drop_table('word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=45), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.drop_table('library_word')
    # ### end Alembic commands ###
